# Generated by Django 5.0.7 on 2024-07-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordresearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordsRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
    ]
