# Generated by Django 5.0.7 on 2024-07-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordresearch', '0002_keywordsrank'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordsrank',
            name='Mysite',
            field=models.CharField(default='default_site', max_length=100),
        ),
        migrations.AddField(
            model_name='keywordsrank',
            name='comparator1',
            field=models.CharField(default='default_comparator1', max_length=100),
        ),
        migrations.AddField(
            model_name='keywordsrank',
            name='comparator2',
            field=models.CharField(default='default_comparator2', max_length=100),
        ),
        migrations.AddField(
            model_name='keywordsrank',
            name='myrank',
            field=models.CharField(default='default_rank', max_length=100),
        ),
        migrations.AddField(
            model_name='keywordsrank',
            name='rank_comparator1',
            field=models.CharField(default='default_rank_comparator1', max_length=100),
        ),
        migrations.AddField(
            model_name='keywordsrank',
            name='rank_comparator2',
            field=models.CharField(default='default_rank_comparator2', max_length=100),
        ),
    ]
