# Generated by Django 5.0.7 on 2024-07-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywordresearch', '0004_alter_keywordsrank_mysite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(default='-', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='keywordsrank',
            name='comparator1',
        ),
        migrations.RemoveField(
            model_name='keywordsrank',
            name='comparator2',
        ),
    ]
